### PR TITLE
resume-edits

### PR DESCRIPTION
**Pull request by calebgmahala**
Make sure everything is spelled right

### CODE REVIEW

**Review by Starvosky — APPROVED** [review]
Good spelling.

**Comment by calebgmahala** [comment]
I think your input is valid @Starvosky thanks.

**Comment by Starvosky** [comment]
Thank you ghost rider. ;^)  
@calebgmahala

**Comment by edgararodriguez** [comment]
this nice i like it u need betta typign tho

**Comment by calebgmahala** [comment]
@edgararodriguez thanks!

**Review by daviirose — COMMENTED** [review]
Its good

**Review by edgararodriguez — APPROVED** [review]
This is nice

**Review by daviirose — APPROVED** [review]
Its good

**Comment by calebgmahala** [comment]
Alright Ill merge

**Pull request merged**
