### PR TITLE
finished header

### PR DESCRIPTION
**Pull request by calebgmahala**
Make sure header meets requirements. Make sure it is coded correctly and efficiently. I added the CSS reset so everything else will look weird. I set up me header.

### CODE REVIEW

**Review by Starvosky — APPROVED** [review]
Looks good I don't see any errors. Possibly get more reviews before merging tho.

**Comment by calebgmahala** [comment]
Alright I'll wait for d rose

**Review by daviirose — APPROVED** [review]
It looks great but what is the purpose of the all tags listed in big section, remind me

**Comment by calebgmahala** [comment]
So I can make the page white. Otherwise I can't do it

**Comment by calebgmahala** [comment]
If you look at the class on it and the css styles on that class It makes a little more sense.

**Comment by daviirose** [comment]
Show me

**Pull request merged**
